import Navbar from './Components/Navbar'
import Footer from './Footer'
import { AuthProvider } from './Provider'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Medinova Hospital LTds',
  description: 'Generated by create next app',
}


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar></Navbar>
        <AuthProvider>
        {children}
        </AuthProvider>
        <Footer></Footer>
        </body>
    </html>
  )
}
